[project]
name = "13-basic-security"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.1",
    "uvicorn>=0.35.0",
]
